"""
Hypothesis generation and management.

In the future, this will use LLM to:
1. Analyze all evidence for an Ask
2. Identify competing explanations
3. Calculate probability distributions
4. Map evidence to hypotheses with impact scores
5. Update automatically when new evidence arrives
"""
from typing import List, Dict, Any
from datetime import datetime
from .models import Ask, Answer


def generate_hypotheses_for_ask(ask: Ask, answers: List[Answer]) -> List[Dict[str, Any]]:
    """
    Generate competing hypotheses for an Ask based on its evidence.

    TODO: Replace with LLM-based synthesis that:
    - Reads all answer synopses
    - Identifies logical clusters (competing explanations)
    - Calculates Bayesian probability updates
    - Assigns evidence to hypotheses with impact scores

    For now, returns hardcoded hypotheses for the Jimmy Lai case.
    """

    # Temporary hardcoded mapping for Jimmy Lai case
    # In production, this should be stored in DB or generated by LLM
    if ask.id == "ask-jimmy-lai":
        return get_jimmy_lai_hypotheses()

    # Default: generate basic hypotheses from evidence
    return generate_default_hypotheses(ask, answers)


def get_jimmy_lai_hypotheses() -> List[Dict[str, Any]]:
    """Temporary hardcoded hypotheses for Jimmy Lai case"""
    return [
        {
            "id": "h1",
            "statement": "Trump raised issue privately, no public mention",
            "probability": 51,
            "supporting_evidence": [
                {"id": "ans-1", "label": "#1 Zaobao prediction", "type": "supporting", "impact": 18, "number": 1},
                {"id": "ans-4", "label": "#4 Family sources", "type": "supporting", "impact": 20, "number": 4},
                {"id": "ans-5", "label": "#5 Owen Jensen WH official claim", "type": "supporting", "impact": 13, "number": 5},
            ],
            "refuting_evidence": [
                {"id": "ans-2", "label": "#2 Official video transcript", "type": "against", "impact": -15, "number": 2},
            ],
            "context_evidence": [],
            "comment_count": 12,
        },
        {
            "id": "h2",
            "statement": "Trump didn't raise it, family/activists misunderstood",
            "probability": 22,
            "supporting_evidence": [
                {"id": "ans-2", "label": "#2 Official transcript silent", "type": "supporting", "impact": 12, "number": 2},
                {"id": "ans-3", "label": "#3 Chinese social media denial", "type": "supporting", "impact": 10, "number": 3},
            ],
            "refuting_evidence": [
                {"id": "ans-4", "label": "#4 Family claims", "type": "against", "impact": -8, "number": 4},
            ],
            "context_evidence": [],
            "comment_count": 8,
        },
        {
            "id": "h3",
            "statement": "Coordinated information warfare (both sides obscuring truth)",
            "probability": 18,
            "supporting_evidence": [
                {"id": "ans-3", "label": "#3 Chinese denial campaign", "type": "supporting", "impact": 15, "number": 3},
            ],
            "refuting_evidence": [],
            "context_evidence": [
                {"id": "ans-2", "label": "#2 Both govts avoid confirmation", "type": "context", "impact": 3, "number": 2},
            ],
            "comment_count": 15,
        },
        {
            "id": "h4",
            "statement": "Raised but officials bluffing/exaggerating details",
            "probability": 9,
            "supporting_evidence": [
                {"id": "ans-1", "label": "#1 Prediction (not confirmed)", "type": "supporting", "impact": 6, "number": 1},
            ],
            "refuting_evidence": [
                {"id": "ans-4", "label": "#4 Family statements seem clear", "type": "against", "impact": -3, "number": 4},
            ],
            "context_evidence": [],
            "comment_count": 5,
        },
    ]


def generate_default_hypotheses(ask: Ask, answers: List[Answer]) -> List[Dict[str, Any]]:
    """
    Generate basic hypotheses when no custom mapping exists.

    Simple heuristic:
    - Create 2-3 hypotheses based on evidence clustering
    - Assign probabilities based on vote scores
    """
    if not answers:
        return []

    # Sort by vote score
    sorted_answers = sorted(answers, key=lambda a: a.vote_score, reverse=True)

    # Create simple "confirmed" vs "disputed" hypotheses
    return [
        {
            "id": "h1",
            "statement": "Primary claim is supported by evidence",
            "probability": 60,
            "supporting_evidence": [
                {
                    "id": sorted_answers[0].id,
                    "label": f"#{i+1} {sorted_answers[0].synopsis[:30]}...",
                    "type": "supporting",
                    "impact": 30,
                    "number": i+1,
                }
                for i, ans in enumerate(sorted_answers[:2])
            ],
            "refuting_evidence": [],
            "context_evidence": [],
            "comment_count": sum(len(a.comments) for a in answers[:2]),
        },
        {
            "id": "h2",
            "statement": "Evidence is inconclusive or contradictory",
            "probability": 40,
            "supporting_evidence": [],
            "refuting_evidence": [
                {
                    "id": sorted_answers[0].id,
                    "label": f"#{i+1} Evidence unclear",
                    "type": "against",
                    "impact": -15,
                    "number": i+1,
                }
                for i, ans in enumerate(sorted_answers[:1])
            ],
            "context_evidence": [],
            "comment_count": sum(len(a.comments) for a in answers),
        },
    ]


def calculate_evidence_impact(
    answer: Answer,
    hypothesis: str,
    all_answers: List[Answer]
) -> float:
    """
    Calculate how much an answer impacts a hypothesis probability.

    TODO: Use LLM to:
    - Analyze semantic similarity between answer and hypothesis
    - Consider source quality (primary vs secondary)
    - Factor in community validation (upvotes, comments)
    - Apply Bayesian updating

    For now, simple heuristic based on votes and novelty.
    """
    base_impact = 10.0

    # Adjust by vote score
    vote_factor = 1.0 + (answer.vote_score / 10.0)

    # Adjust by novelty
    novelty_multiplier = {
        "high": 1.5,
        "medium": 1.0,
        "low": 0.5,
    }.get(answer.novelty, 1.0)

    # Adjust by validation
    validation_multiplier = 1.3 if answer.validated else 1.0

    impact = base_impact * vote_factor * novelty_multiplier * validation_multiplier

    return min(impact, 50.0)  # Cap at 50%


def get_hypothesis_trajectory(ask_id: str, hypothesis_id: str) -> List[Dict[str, Any]]:
    """
    Get the probability trajectory for a hypothesis over time.

    Returns list of {timestamp, probability, trigger_event} points
    showing how the hypothesis probability changed as evidence arrived.

    TODO: Calculate from actual evidence timeline
    """
    if ask_id == "ask-jimmy-lai":
        return get_jimmy_lai_trajectory(hypothesis_id)

    return []


def get_jimmy_lai_trajectory(hypothesis_id: str) -> List[Dict[str, Any]]:
    """Mock trajectory data for Jimmy Lai case - shows how probabilities evolved"""

    trajectories = {
        "h1": [  # "Trump raised privately"
            {"timestamp": "2025-10-25T06:14:00Z", "probability": 35, "event": "Initial prediction (Zaobao)"},
            {"timestamp": "2025-10-28T14:30:00Z", "probability": 28, "event": "Official transcript shows no mention"},
            {"timestamp": "2025-10-29T08:15:00Z", "probability": 42, "event": "Family sources confirm private discussion"},
            {"timestamp": "2025-10-30T16:20:00Z", "probability": 45, "event": "Advocacy groups corroborate"},
            {"timestamp": "2025-10-31T01:11:00Z", "probability": 51, "event": "Owen Jensen WH official claim"},
        ],
        "h2": [  # "Didn't raise it"
            {"timestamp": "2025-10-25T06:14:00Z", "probability": 20, "event": "Initial skepticism"},
            {"timestamp": "2025-10-28T14:30:00Z", "probability": 35, "event": "Official transcript silent"},
            {"timestamp": "2025-10-29T08:15:00Z", "probability": 28, "event": "Family sources emerge"},
            {"timestamp": "2025-10-30T16:20:00Z", "probability": 25, "event": "Chinese denial campaign"},
            {"timestamp": "2025-10-31T01:11:00Z", "probability": 22, "event": "WH claim reduces this"},
        ],
        "h3": [  # "Information warfare"
            {"timestamp": "2025-10-25T06:14:00Z", "probability": 15, "event": "Initial framing"},
            {"timestamp": "2025-10-28T14:30:00Z", "probability": 18, "event": "Official silence noted"},
            {"timestamp": "2025-10-29T08:15:00Z", "probability": 20, "event": "Conflicting claims emerge"},
            {"timestamp": "2025-10-30T16:20:00Z", "probability": 25, "event": "Chinese denial campaign detected"},
            {"timestamp": "2025-10-31T01:11:00Z", "probability": 18, "event": "WH claim shifts narrative"},
        ],
        "h4": [  # "Officials bluffing"
            {"timestamp": "2025-10-25T06:14:00Z", "probability": 30, "event": "Prediction uncertainty"},
            {"timestamp": "2025-10-28T14:30:00Z", "probability": 19, "event": "Transcript reality check"},
            {"timestamp": "2025-10-29T08:15:00Z", "probability": 10, "event": "Family sources credible"},
            {"timestamp": "2025-10-30T16:20:00Z", "probability": 5, "event": "Multiple sources agree"},
            {"timestamp": "2025-10-31T01:11:00Z", "probability": 9, "event": "Anonymous source raises questions"},
        ],
    }

    return trajectories.get(hypothesis_id, [])
